src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return response()->redirectTo('login');
});

//Auth & account related URLs
Auth::routes();
Route::get('account/profile', 'ProfileController@showProfile')->name('profile.show');
Route::patch('account/profile', 'ProfileController@updateProfile')->name('profile.update');


Route::get('dashboard', 'DashboardController')->name('dashboard')->middleware('auth');

//books
Route::get('book/xml', 'Admin\BookController@xmlDownload')->name('book.xml');
Route::get('book/csv', 'Admin\BookController@csvDownload')->name('book.csv');
Route::resource('book', 'Admin\BookController')->except('show');

//author
Route::get('author/xml', 'Admin\AuthorController@xmlDownload')->name('author.xml');
Route::get('author/csv', 'Admin\AuthorController@csvDownload')->name('author.csv');
Route::resource('author', 'Admin\AuthorController')->except('show');

Route::resource('tag', 'Admin\TagController')->except('show');

src/app/Models/Tag.php
<?php

namespace App\Models;

use App\Components\SearchEveryWhere;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
    use SoftDeletes, SearchEveryWhere;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];


    /**
     * Columns white listed for the global search
     */
    protected $searchable = [
        'name'
    ];


    /**
     * Get the books with this tag.
     */
    public function books(): \Illuminate\Database\Eloquent\Relations\BelongsToMany
    {
        return $this->belongsToMany(Book::class);
    }
}

src/app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Auth\VerificationController;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class TagController extends VerificationController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if (! Gate::allows('list-tag')) {
            abort(403);
        }

        return view('admin.tags.index', [
            'pageTitle' => 'Tags',
            'models' => Tag::withCount('books')->latest()->searchInColumns($request->q)->paginate()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        if (! Gate::allows('create-tag')) {
            abort(403);
        }

        return view('admin.tags._form', [
            'pageTitle' => "Create Tag", //page title

            'routeBaseName' => 'tag',
            'routeName' => 'tag.store',

            'resourceName' => 'tag',

            'actionPerforming' => 'create'
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (! Gate::allows('create-tag')) {
            abort(403);
        }

        $tag = Tag::Create($request->only('name'));

        if( $tag ){

            $tag->books()->sync($request->books);

            flash('<b>Success!</b> Tag was created!')->success();
            return redirect()->route('tag.edit', $tag->id);
        }else{
            flash('<b>Opps!</b> Something went wrong!')->error();
            return back()->withInput();
        }
    }



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('view-tag')) {
            abort(403);
        }

        return view('admin.tags._form', [
            'pageTitle' => "Update Tag", //page title

            'model' => \App\Models\Tag::findOrFail($id),

            'routeBaseName' => 'tag',
            'routeName' => 'tag.update', //

            'resourceName' => 'tag',

            'actionPerforming' => 'update'
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (! Gate::allows('update-tag')) {
            abort(403);
        }

        $tag = Tag::findOrFail($id);
        $tag->fill($request->only('name'));

        if( $tag->save() ){ //try to save

            $tag->books()->sync($request->books);

            flash('<b>Success!</b> Tag was update!')->success();
            return redirect()->route('tag.edit', $id);
        }else{
            flash('<b>Opps!</b> Something went wrong!')->error();
            return back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('delete-tag')) {
            abort(403);
        }

        if( Tag::findOrFail($id)->delete() ){
            flash('<b>Success!</b> Tag was deleted!')->success();
            return redirect()->route('tag.index');
        }else{
            flash('<b>Opps!</b> Something went wrong!')->error();
            return back()->withInput();
        }
    }
}

src/resources/views/admin/tags/_form.blade.php
@extends('adminlte::page')

@section('title', $pageTitle)

@section('content_header')
    <h1>{{$pageTitle}}</h1>
@stop

@include('components.select2-libraries')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                    @if(isset($model))
                        {{ Form::model($model, ['url' => route($routeName, $model->id), 'method' => 'PATCH']) }}
                    @else
                        {{ Form::open(['url' => route($routeName), 'method' => 'POST']) }}
                    @endif


                    <!-- Row -->
                        <div class="row">

                            <!-- col-md-6 -->
                            <div class="col-md-6">

                                <!-- Text input-->
                                <div class="form-group">
                                    <label class="col-md-12 control-label" for="name">Name of The Tag</label>
                                    <div class="col-md-12">
                                        {{ Form::text('name', null, ['placeholder'=>"Tag Name", 'class'=>"form-control input-md", 'required'=>""]) }}
                                        @include('components.field-error-msg', ['field'=>'name'])
                                    </div>
                                </div>

                            </div>
                            <!-- End col-md-6 -->

                            <!-- col-md-6 -->
                            <div class="col-md-6">

                                <!-- Select Basic -->
                                <div class="form-group">
                                    <label class="col-md-12 control-label" for="books[]">Books</label>
                                    <div class="col-md-12">
                                        {{  Form::select('books[]', \App\Models\Book::all()->pluck('name', 'id'), null, ['class'=>"select2 form-control", 'multiple']) }}
                                        @include('components.field-error-msg', ['field'=>'books'])
                                    </div>
                                </div>

                            </div>
                            <!-- End col-md-6 -->

                            <div class="col-md-4 offset-md-4 col-sm-12">
                                <br>

                                @include('components.resource-form-buttons')

                            </div>

                        </div>
                        <!-- End Row -->


                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

src/resources/views/admin/tags/index.blade.php
@extends('adminlte::page')

@section('title', $pageTitle)

@section('content_header')
    <h1>{{$pageTitle}}</h1>
@stop

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">

                        {{$models->links()}}

                        <table class="table">
                            <tr>
                                <th>Name</th>
                                <th>Books</th>
                            </tr>
                            @foreach($models as $Model)
                                <tr>
                                    <td><a href="{{route('tag.edit', $Model->id)}}">{{$Model->name}}</td>
                                    {{--TODO::add search filter in books for the tag--}}
                                    <td>{{$Model->books_count}}</td>
                                </tr>
                            @endforeach
                        </table>

                        {{$models->links()}}

                    </div>
                </div>
            </div>
        </div>
    </div>
@stop